### PR TITLE
Separate app filtering and wildcard PFCP-based STC scenarios

### PR DESCRIPTION
**Pull request by daniele-moro**
Separate PFCP-based STC scenarios for forwarding and app filtering:
- `pfcp-forwarding`: wildcard SDF filter, no application filtering.
- `pfcp-app-filtering`: explicit SDF filter. With positive and negative test.

### CODE REVIEW

**Comment by daniele-moro** [comment]
retest this please

**Comment by daniele-moro** [comment]
This is failing because of some issue in the grpc channel being deleted. Should be fixed when we merge this: https://github.com/stratum/fabric-tna/pull/482 or a fix for this issue.

**Review by ccascone — APPROVED** [review]

**Comment by daniele-moro** [comment]
retest this please

**Comment by daniele-moro** [comment]
retest this please

**Comment by ccascone** [comment]
Do we want to merge this? Any idea why pfcp tests are failing?

**Comment by daniele-moro** [comment]
Yes, I would like to merge it. I was doing some tests yesterday and I haven't found the reason for the failure. Running scenarios one by one seems to work fine, while the `pfcp-smoke` fails. I need to spend some more time on this.

**Comment by daniele-moro** [comment]
Found the issue. The problem is due to the fact that PFCPiface does not clear the applications table. @osinstom is this the expected behavior of PFCPiface?

**Pull request merged**
